Lyte.Component.register("welcome-comp", {
    data: function() {
        return {
            features: Lyte.attr("array"),
            navItems: Lyte.attr('array', {
                default: [{
                        'name': 'Module 1',
                        'key': 'mod1',
                        'value': 'mod1'
                    }, {
                        'name': 'Module 2',
                        'key': 'mod2',
                        'value': 'mod2'
                    }, {
                        'name': 'Module 3',
                        'key': 'mod3',
                        'value': 'mod3'
                    }, {
                        'name': 'Module 4',
                        'key': 'mod4',
                        'value': 'mod4'
                    },
                    {
                        'name': 'Module 13',
                        'key': 'mod13',
                        'value': 'mod13'
                    }, {
                        'name': 'Module 23',
                        'key': 'mod23',
                        'value': 'mod23'
                    }, {
                        'name': 'Module 33',
                        'key': 'mod33',
                        'value': 'mod33'
                    }, {
                        'name': 'Module 43',
                        'key': 'mod43',
                        'value': 'mod43'
                    },
                    {
                        'name': 'Module 14',
                        'key': 'mod14',
                        'value': 'mod14'
                    }, {
                        'name': 'Module 24',
                        'key': 'mod24',
                        'value': 'mod24'
                    }, {
                        'name': 'Module 34',
                        'key': 'mod34',
                        'value': 'mod34'
                    }, {
                        'name': 'Module 44',
                        'key': 'mod44',
                        'value': 'mod44'
                    }
                ]
            }),
            layoutData: Lyte.attr('object', {
                default: {
                    "sections": [{
                        "fsm_section_type": "simple",
                        "fsm_section_name": "section1",
                        "group_number": 1,
                        "column_count": 1,
                        "fields": [{
                                "fsm_advanced_search": null,
                                "fsm_min_date": "01-09-2020 00:00:00",
                                "fsm_enable_quick_create": null,
                                "fsm_date_range": "No range",
                                "field_label": null,
                                "fsm_formula": null,
                                "tooltip": null,
                                "fsm_data_type": "datetime",
                                "required": false,
                                "fsm_max_size": null,
                                "id": "1005000000082594",
                                "fsm_max_selection_allowed": null,
                                "fsm_sort_order": "asc",
                                "module": "Assets",
                                "is_fsm_field_configured": false,
                                "view_type": {
                                    "quickcreate": false,
                                    "read": true,
                                    "edit": true,
                                    "create": true
                                },
                                "fsm_round_function": null,
                                "fsm_search_by": null,
                                "fsm_max_date": "01-09-2020 00:00:00",
                                "fsm_validation_rule": null,
                                "fsm_read_only": {
                                    "edit": false,
                                    "create": false
                                },
                                "api_name": "Installation_Date",
                                "column_number": 1,
                                "fsm_search_result": null,
                                "fsm_lookup_icon": null,
                                "fsm_max_digits_allowed": null,
                                "pick_list_values": null,
                                "fsm_date_format": "MMM D, YYYY hh:mm A",
                                "fsm_address_field_map": null,
                                "fsm_section_name": "section1",
                                "fsm_search_enabled": true,
                                "fsm_advanced_search_result": null,
                                "fsm_visible": true,
                                "ui_type": null,
                                "fsm_upload_url": null,
                                "fsm_quick_create_label": null,
                                "fsm_field_label": "Installation Date",
                                "lookup": {},
                                "fsm_on_cancel": null,
                                "fsm_on_select": {},
                                "length": 120,
                                "default_value": null,
                                "fsm_currency_format": null,
                                "sequence_number": 10,
                                "parent_sequence_number": null,
                                "fsm_field_api_name": "Assets___Installation_Date",
                                "data_type": "datetime",
                                "fsm_refer_from_fields": null,
                                "decimal_place": "2"
                            },
                            {
                                "fsm_advanced_search": null,
                                "fsm_min_date": null,
                                "fsm_enable_quick_create": null,
                                "fsm_date_range": null,
                                "field_label": "Phone 1",
                                "fsm_formula": null,
                                "tooltip": null,
                                "fsm_data_type": "phone",
                                "required": false,
                                "fsm_max_size": null,
                                "id": "1005000000103060",
                                "fsm_max_selection_allowed": null,
                                "fsm_sort_order": "asc",
                                "module": "Assets",
                                "is_fsm_field_configured": false,
                                "view_type": {
                                    "quickcreate": false,
                                    "read": true,
                                    "edit": true,
                                    "create": true
                                },
                                "fsm_round_function": null,
                                "fsm_search_by": null,
                                "fsm_max_date": null,
                                "fsm_validation_rule": null,
                                "fsm_read_only": {
                                    "quickcreate": false,
                                    "edit": false,
                                    "create": false
                                },
                                "api_name": "Phone_1__C",
                                "unique": {},
                                "column_number": 1,
                                "fsm_search_result": null,
                                "fsm_lookup_icon": null,
                                "fsm_max_digits_allowed": null,
                                "pick_list_values": null,
                                "fsm_date_format": null,
                                "fsm_address_field_map": null,
                                "fsm_section_name": "section1",
                                "fsm_search_enabled": true,
                                "fsm_advanced_search_result": null,
                                "ui_type": null,
                                "fsm_visible": true,
                                "fsm_upload_url": null,
                                "fsm_quick_create_label": null,
                                "fsm_field_label": "Phone 1",
                                "lookup": {},
                                "fsm_on_cancel": null,
                                "fsm_on_select": {},
                                "length": 30,
                                "default_value": null,
                                "fsm_currency_format": null,
                                "sequence_number": 12,
                                "parent_sequence_number": null,
                                "fsm_field_api_name": "Assets___Phone_1__C",
                                "data_type": "phone",
                                "fsm_refer_from_fields": null,
                                "decimal_place": "2"
                            },
                            {
                                "fsm_advanced_search": null,
                                "fsm_min_date": null,
                                "fsm_enable_quick_create": null,
                                "fsm_date_range": null,
                                "field_label": null,
                                "fsm_formula": null,
                                "tooltip": null,
                                "fsm_data_type": "textarea",
                                "required": false,
                                "fsm_max_size": null,
                                "id": "1005000000082619",
                                "fsm_max_selection_allowed": null,
                                "fsm_sort_order": "asc",
                                "module": "Assets",
                                "is_fsm_field_configured": false,
                                "view_type": {
                                    "quickcreate": true,
                                    "read": true,
                                    "edit": true,
                                    "create": true
                                },
                                "fsm_round_function": null,
                                "fsm_search_by": null,
                                "fsm_max_date": null,
                                "fsm_validation_rule": null,
                                "fsm_read_only": {
                                    "edit": false,
                                    "create": false
                                },
                                "api_name": "Description",
                                "column_number": 1,
                                "fsm_search_result": null,
                                "fsm_lookup_icon": null,
                                "fsm_max_digits_allowed": null,
                                "pick_list_values": null,
                                "fsm_date_format": null,
                                "fsm_address_field_map": null,
                                "fsm_section_name": "section1",
                                "fsm_search_enabled": true,
                                "fsm_advanced_search_result": null,
                                "fsm_visible": true,
                                "ui_type": null,
                                "fsm_upload_url": null,
                                "fsm_quick_create_label": null,
                                "fsm_field_label": "Description",
                                "lookup": {},
                                "fsm_on_cancel": null,
                                "fsm_on_select": {},
                                "length": 2000,
                                "default_value": null,
                                "fsm_currency_format": null,
                                "sequence_number": 2,
                                "field_validation_patterns": [
                                    "[0-9a-zA-Z_%~\\\\{\\}\\|&quot;\\*\\^\\#\\-\\.\\$@\\?\\,\\&amp;\\+\\(\\)\\[\\]\\:\\'/\\!]"
                                ],
                                "parent_sequence_number": null,
                                "fsm_field_api_name": "Assets___Description",
                                "data_type": "textarea",
                                "fsm_refer_from_fields": null,
                                "decimal_place": "2"
                            },
                            {
                                "fsm_advanced_search": null,
                                "fsm_min_date": null,
                                "fsm_enable_quick_create": null,
                                "fsm_address_field_map": null,
                                "fsm_date_range": null,
                                "fsm_section_name": "section1",
                                "field_label": null,
                                "fsm_formula": null,
                                "tooltip": null,
                                "fsm_data_type": "ownerlookup",
                                "fsm_search_enabled": true,
                                "fsm_advanced_search_result": null,
                                "required": false,
                                "fsm_visible": true,
                                "ui_type": null,
                                "fsm_upload_url": null,
                                "fsm_quick_create_label": null,
                                "fsm_max_size": null,
                                "id": "1005000000070134",
                                "fsm_field_label": "Assets Owner",
                                "fsm_max_selection_allowed": null,
                                "fsm_sort_order": "asc",
                                "lookup": {},
                                "fsm_on_cancel": null,
                                "fsm_on_select": {},
                                "module": "Assets",
                                "is_fsm_field_configured": false,
                                "view_type": {
                                    "quickcreate": false,
                                    "read": true,
                                    "edit": true,
                                    "create": false
                                },
                                "default_value": null,
                                "fsm_currency_format": null,
                                "fsm_round_function": null,
                                "fsm_search_by": null,
                                "sequence_number": 13,
                                "fsm_max_date": null,
                                "fsm_validation_rule": null,
                                "parent_sequence_number": null,
                                "fsm_field_api_name": "Assets___Owner",
                                "fsm_read_only": {
                                    "edit": false,
                                    "create": false
                                },
                                "api_name": "Owner",
                                "data_type": "ownerlookup",
                                "column_number": 1,
                                "fsm_search_result": null,
                                "fsm_lookup_icon": null,
                                "fsm_max_digits_allowed": null,
                                "fsm_refer_from_fields": null,
                                "decimal_place": "2",
                                "pick_list_values": null,
                                "fsm_date_format": null
                            },
                            {
                                "fsm_advanced_search": null,
                                "fsm_min_date": null,
                                "fsm_enable_quick_create": null,
                                "fsm_date_range": "Next 30 Days",
                                "field_label": "Date 1",
                                "fsm_formula": null,
                                "tooltip": null,
                                "fsm_data_type": "date",
                                "required": false,
                                "fsm_max_size": null,
                                "id": "1005000000103042",
                                "fsm_max_selection_allowed": null,
                                "fsm_sort_order": "asc",
                                "module": "Assets",
                                "is_fsm_field_configured": false,
                                "view_type": {
                                    "quickcreate": false,
                                    "read": true,
                                    "edit": true,
                                    "create": true
                                },
                                "fsm_round_function": null,
                                "fsm_search_by": null,
                                "fsm_max_date": null,
                                "fsm_validation_rule": null,
                                "fsm_read_only": {
                                    "quickcreate": false,
                                    "edit": false,
                                    "create": false
                                },
                                "api_name": "Date_1__C",
                                "column_number": 1,
                                "fsm_search_result": null,
                                "fsm_lookup_icon": null,
                                "fsm_max_digits_allowed": null,
                                "pick_list_values": null,
                                "fsm_date_format": "MMM D, YYYY",
                                "fsm_address_field_map": null,
                                "fsm_section_name": "section1",
                                "fsm_search_enabled": true,
                                "fsm_advanced_search_result": null,
                                "ui_type": null,
                                "fsm_visible": true,
                                "fsm_upload_url": null,
                                "fsm_quick_create_label": null,
                                "fsm_field_label": "Date 1",
                                "lookup": {},
                                "fsm_on_cancel": null,
                                "fsm_on_select": {},
                                "length": 20,
                                "default_value": null,
                                "fsm_currency_format": null,
                                "sequence_number": 9,
                                "parent_sequence_number": null,
                                "fsm_field_api_name": "Assets___Date_1__C",
                                "data_type": "date",
                                "fsm_refer_from_fields": null,
                                "decimal_place": "2"
                            },
                            {
                                "fsm_advanced_search": true,
                                "fsm_enable_quick_create": true,
                                "fsm_min_date": null,
                                "fsm_date_range": null,
                                "field_label": null,
                                "fsm_formula": null,
                                "tooltip": null,
                                "fsm_data_type": "address",
                                "required": false,
                                "fsm_max_size": null,
                                "id": "1005000000087610",
                                "fsm_max_selection_allowed": null,
                                "fsm_sort_order": "asc",
                                "module": "Assets",
                                "lookup_module_fields": {
                                    "Tax_Percentage": "double",
                                    "Owner": "ownerlookup",
                                    "Company": "lookup",
                                    "Customer": "lookup",
                                    "Tax_Authority": "text",
                                    "Latitude": "double",
                                    "Tax_Id": "text",
                                    "Address_Name": "text",
                                    "Place_of_Supply": "text",
                                    "Name": "autonumber",
                                    "Last_Activity_Time": "datetime",
                                    "Record_Image": "profileimage",
                                    "Unsubscribed_Mode": "picklist",
                                    "Tax_Reg_Number": "text",
                                    "Exchange_Rate": "double",
                                    "Currency": "picklist",
                                    "Street": "text",
                                    "Asset": "lookup",
                                    "Zip_Code": "text",
                                    "Tax_Name": "text",
                                    "Tax_Exemption_Id": "text",
                                    "Street2": "text",
                                    "Territory": "lookup",
                                    "Unsubscribed_Time": "datetime",
                                    "GST_Treatment": "text",
                                    "City": "text",
                                    "Longitude": "double",
                                    "Tax_Authority_Id": "text",
                                    "VAT_Treatment": "text",
                                    "State": "text",
                                    "Country": "text",
                                    "Is_Record_Duplicate": "boolean",
                                    "Tag": "text",
                                    "Taxable": "picklist"
                                },
                                "is_fsm_field_configured": false,
                                "view_type": {
                                    "quickcreate": false,
                                    "read": true,
                                    "edit": true,
                                    "create": true
                                },
                                "fsm_round_function": null,
                                "fsm_search_by": "Address_Name",
                                "fsm_max_date": null,
                                "fsm_validation_rule": null,
                                "fsm_read_only": {
                                    "edit": false,
                                    "create": false
                                },
                                "api_name": "Address",
                                "column_number": 1,
                                "fsm_search_result": [
                                    [
                                        "Address_Name",
                                        "City",
                                        "Country",
                                        "Street",
                                        "Street2",
                                        "Zip_Code"
                                    ]
                                ],
                                "fsm_lookup_icon": "zp-li-billing-address-icon",
                                "fsm_max_digits_allowed": null,
                                "pick_list_values": null,
                                "fsm_date_format": null,
                                "quick_create_action": "Render_lookup.buttonFunction",
                                "fsm_address_field_map": null,
                                "fsm_section_name": "section1",
                                "fsm_search_enabled": true,
                                "fsm_advanced_search_result": null,
                                "fsm_visible": true,
                                "ui_type": null,
                                "fsm_upload_url": null,
                                "fsm_quick_create_label": null,
                                "fsm_field_label": "Address",
                                "fsm_advanced_function": "Render_lookup.customLookupPopup",
                                "lookup": {
                                    "display_label": "Assets",
                                    "api_name": "Assets",
                                    "module": {
                                        "api_name": "Addresses",
                                        "id": "1005000000051044"
                                    },
                                    "id": "1005000000087614"
                                },
                                "fsm_on_cancel": null,
                                "fsm_on_select": {},
                                "defaultSearch": true,
                                "default_value": null,
                                "fsm_currency_format": null,
                                "sequence_number": 5,
                                "parent_sequence_number": null,
                                "fsm_field_api_name": "Assets___Address",
                                "data_type": "lookup",
                                "fsm_refer_from_fields": null,
                                "decimal_place": "2"
                            },
                            {
                                "fsm_advanced_search": null,
                                "fsm_min_date": null,
                                "fsm_enable_quick_create": null,
                                "fsm_date_range": null,
                                "field_label": null,
                                "fsm_formula": null,
                                "tooltip": null,
                                "fsm_data_type": "text",
                                "required": true,
                                "fsm_max_size": null,
                                "id": "1005000000070132",
                                "fsm_max_selection_allowed": null,
                                "fsm_sort_order": "asc",
                                "module": "Assets",
                                "is_fsm_field_configured": false,
                                "view_type": {
                                    "quickcreate": true,
                                    "read": true,
                                    "edit": true,
                                    "create": true
                                },
                                "fsm_round_function": null,
                                "fsm_search_by": null,
                                "fsm_max_date": null,
                                "fsm_validation_rule": null,
                                "fsm_read_only": {
                                    "edit": false,
                                    "create": false
                                },
                                "api_name": "Name",
                                "column_number": 1,
                                "fsm_search_result": null,
                                "fsm_lookup_icon": null,
                                "fsm_max_digits_allowed": null,
                                "pick_list_values": null,
                                "fsm_date_format": null,
                                "fsm_address_field_map": null,
                                "fsm_section_name": "section1",
                                "fsm_search_enabled": true,
                                "fsm_advanced_search_result": null,
                                "fsm_visible": true,
                                "ui_type": null,
                                "fsm_upload_url": null,
                                "fsm_quick_create_label": null,
                                "fsm_field_label": "Asset Name",
                                "lookup": {},
                                "fsm_on_cancel": null,
                                "fsm_on_select": {},
                                "length": 120,
                                "default_value": null,
                                "fsm_currency_format": null,
                                "sequence_number": 1,
                                "field_validation_patterns": [
                                    "[0-9a-zA-Z_%~\\\\{\\}\\|&quot;\\*\\^\\#\\-\\.\\$@\\?\\,\\&amp;\\+\\(\\)\\[\\]\\:\\'/\\!]"
                                ],
                                "parent_sequence_number": null,
                                "fsm_field_api_name": "Assets___Name",
                                "data_type": "text",
                                "fsm_refer_from_fields": null,
                                "decimal_place": "2"
                            },
                            {
                                "fsm_advanced_search": null,
                                "fsm_min_date": null,
                                "fsm_enable_quick_create": null,
                                "fsm_date_range": null,
                                "field_label": "Email 1",
                                "fsm_formula": null,
                                "tooltip": null,
                                "fsm_data_type": "email",
                                "required": false,
                                "fsm_max_size": null,
                                "id": "1005000000103037",
                                "fsm_max_selection_allowed": null,
                                "fsm_sort_order": "asc",
                                "module": "Assets",
                                "is_fsm_field_configured": false,
                                "view_type": {
                                    "quickcreate": false,
                                    "read": true,
                                    "edit": true,
                                    "create": true
                                },
                                "fsm_round_function": null,
                                "fsm_search_by": null,
                                "fsm_max_date": null,
                                "fsm_validation_rule": null,
                                "fsm_read_only": {
                                    "quickcreate": false,
                                    "edit": false,
                                    "create": false
                                },
                                "api_name": "Email_1__C",
                                "unique": {},
                                "column_number": 1,
                                "fsm_search_result": null,
                                "fsm_lookup_icon": null,
                                "fsm_max_digits_allowed": null,
                                "pick_list_values": null,
                                "fsm_date_format": null,
                                "fsm_address_field_map": null,
                                "fsm_section_name": "section1",
                                "fsm_search_enabled": true,
                                "fsm_advanced_search_result": null,
                                "ui_type": null,
                                "fsm_visible": true,
                                "fsm_upload_url": null,
                                "fsm_quick_create_label": null,
                                "fsm_field_label": "Email 1",
                                "lookup": {},
                                "fsm_on_cancel": null,
                                "fsm_on_select": {},
                                "length": 100,
                                "default_value": null,
                                "fsm_currency_format": null,
                                "sequence_number": 8,
                                "parent_sequence_number": null,
                                "fsm_field_api_name": "Assets___Email_1__C",
                                "data_type": "email",
                                "fsm_refer_from_fields": null,
                                "decimal_place": "2"
                            },
                            {
                                "fsm_advanced_search": null,
                                "fsm_min_date": null,
                                "fsm_enable_quick_create": null,
                                "fsm_date_range": null,
                                "field_label": "Pick list 4",
                                "fsm_formula": null,
                                "tooltip": null,
                                "fsm_data_type": "picklist",
                                "required": false,
                                "fsm_max_size": null,
                                "id": "1005000000103047",
                                "fsm_max_selection_allowed": null,
                                "fsm_sort_order": "asc",
                                "module": "Assets",
                                "is_fsm_field_configured": false,
                                "view_type": {
                                    "quickcreate": false,
                                    "read": true,
                                    "edit": true,
                                    "create": true
                                },
                                "fsm_round_function": null,
                                "fsm_search_by": null,
                                "fsm_max_date": null,
                                "fsm_validation_rule": null,
                                "fsm_read_only": {
                                    "quickcreate": false,
                                    "edit": false,
                                    "create": false
                                },
                                "api_name": "Pick_list_4__C",
                                "column_number": 1,
                                "fsm_search_result": null,
                                "fsm_lookup_icon": null,
                                "fsm_max_digits_allowed": null,
                                "pick_list_values": [{
                                        "display_value": "-None-",
                                        "actual_value": "-None-",
                                        "id": "1005000000103049"
                                    },
                                    {
                                        "display_value": "Option 1",
                                        "actual_value": "Option 1",
                                        "id": "1005000000103051"
                                    },
                                    {
                                        "display_value": "Option 2",
                                        "actual_value": "Option 2",
                                        "id": "1005000000103053"
                                    },
                                    {
                                        "display_value": "Option 3",
                                        "actual_value": "Option 3",
                                        "id": "1005000000103055"
                                    }
                                ],
                                "fsm_date_format": null,
                                "fsm_address_field_map": null,
                                "fsm_section_name": "section1",
                                "fsm_search_enabled": true,
                                "fsm_advanced_search_result": null,
                                "ui_type": null,
                                "fsm_visible": true,
                                "fsm_upload_url": null,
                                "fsm_quick_create_label": null,
                                "fsm_field_label": "Pick list 4",
                                "lookup": {},
                                "fsm_on_cancel": null,
                                "fsm_on_select": {},
                                "length": 120,
                                "default_value": null,
                                "fsm_currency_format": null,
                                "sequence_number": 11,
                                "parent_sequence_number": null,
                                "fsm_field_api_name": "Assets___Pick_list_4__C",
                                "data_type": "picklist",
                                "fsm_refer_from_fields": null,
                                "decimal_place": "2"
                            },
                            {
                                "fsm_advanced_search": null,
                                "fsm_min_date": null,
                                "fsm_enable_quick_create": null,
                                "fsm_date_range": null,
                                "field_label": "Checkbox 2",
                                "fsm_formula": null,
                                "tooltip": null,
                                "fsm_data_type": "boolean",
                                "required": false,
                                "fsm_max_size": null,
                                "id": "1005000000103032",
                                "fsm_max_selection_allowed": null,
                                "fsm_sort_order": "asc",
                                "module": "Assets",
                                "is_fsm_field_configured": false,
                                "view_type": {
                                    "quickcreate": false,
                                    "read": true,
                                    "edit": true,
                                    "create": true
                                },
                                "fsm_round_function": null,
                                "fsm_search_by": null,
                                "fsm_max_date": null,
                                "fsm_validation_rule": null,
                                "fsm_read_only": {
                                    "quickcreate": false,
                                    "edit": false,
                                    "create": false
                                },
                                "api_name": "Checkbox_2__C",
                                "column_number": 1,
                                "fsm_search_result": null,
                                "fsm_lookup_icon": null,
                                "fsm_max_digits_allowed": null,
                                "pick_list_values": null,
                                "fsm_date_format": null,
                                "fsm_address_field_map": null,
                                "fsm_section_name": "section1",
                                "fsm_search_enabled": true,
                                "fsm_advanced_search_result": null,
                                "ui_type": null,
                                "fsm_visible": true,
                                "fsm_upload_url": null,
                                "fsm_quick_create_label": null,
                                "fsm_field_label": "Checkbox 2",
                                "lookup": {},
                                "fsm_on_cancel": null,
                                "fsm_on_select": {},
                                "length": 5,
                                "default_value": null,
                                "fsm_currency_format": null,
                                "sequence_number": 7,
                                "parent_sequence_number": null,
                                "fsm_field_api_name": "Assets___Checkbox_2__C",
                                "data_type": "boolean",
                                "fsm_refer_from_fields": null,
                                "decimal_place": "2"
                            }
                        ],
                        "fsm_section_label": "Asset Information"
                    }]
                }
            })
        }
    },
    methods: {
        "onSave": function(param) {
            console.log(param);
            alert("save function triggered");
        },
        "onCancel": function() {
            alert("cancel function triggerred");
        }
    }
});